### ISSUE TITLE
Socket error

### ISSUE THREAD

**Issue by hellsworth** [canonical/workshops#163]
When you run workshops, we see this socket permissions error that doesn't seem to stand in the way of the user creating a container. The error is an eyesore that we would like to fix before the Ubuntu Summit, if possible.

![image](https://user-images.githubusercontent.com/12970280/198390229-ddc8f256-48c1-4268-a0bd-6ceec7ff7c5d.png)

**Comment by kenvandine** [comment]
It looks like the lxd interface isn't connected
```
snap connect workshops:lxd lxd:lxd
```

**Comment by alexmurray** [comment]
To explain this a bit more - the `lxd` interface doesn't auto-connect by default in snapd, so the snap store has a special declaration for the `workshops` snap to make this happen when the snap is installed from the store. But if you build the snap locally then there is no snap store declaration to tell snapd to auto-connect the interface so then you have to do it manually.

**Comment by jpnurmi** [comment]
@kenvandine Would it be worth it to implement a check if the `lxd` interface is connected and if not, offer a button to do so with help of `snapd.dart`?

**Comment by jpnurmi** [comment]
> @kenvandine Would it be worth it to implement a check if the lxd interface is connected and if not, offer a button to do so with help of snapd.dart?

Never mind, workshops would need `snapd-control` for that...

**Comment by hellsworth** [comment]
Ah ok I can close this issue then :)
